### ISSUE TITLE
[Discussion] Remove Install-Target?

### ISSUE THREAD

**Issue by Curve** [ViennaTools/ViennaCore#1]
ViennaCore contains important CMake Functionality which is lost when installing the project through PackageProject.  
This could cause serious issues in case the user has ViennaCore installed locally and we use `CPMFindPackage`.

I would thus recommend only pulling in this library through `CPMAddPackage` which would make the installation target redundant.  

Thus the question, should we remove the Install Target because it's going to be sort of redundant anyways then?

Or should we split the Core Module up even more? We could then have a CMake Core and another Core which contains things related to the code.

**Comment by tobre1** [comment]
If the install target is removed, the header files will always be included from the source repository, right? 

Does it not make sense to install all headers related to code, but if you want to use the CMake utilities, you have to pull in through `CPMAddPackage`?

**Comment by Curve** [comment]
> Does it not make sense to install all headers related to code, but if you want to use the CMake utilities, you have to pull in through `CPMAddPackage`?

Yes, however I don't think there will be any reason to not do the latter

**Comment by tobre1** [comment]
Yes, you are right, but the header files are then still always included from the repository and not some installed target. What if someone installs, e.g., ViennaLS,  and then removes the build folder? Where are the ViennaCore headers then?

**Comment by Curve** [comment]
> Yes, you are right, but the header files are then still always included from the repository and not some installed target. What if someone installs, e.g., ViennaLS, and then removes the build folder? Where are the ViennaCore headers then?

You are absolutely right, didn't think of that! We should leave it as is then and simply always pull in `ViennaCore` through `CPMAddPackage`
