### ISSUE TITLE
[Discussion] Naming scheme and namespaces

### ISSUE THREAD

**Issue by tobre1** [ViennaTools/ViennaCore#2]
I am still not sure about the naming scheme in the ViennaCore library. 

I have now prefixed all files with `vt` (ViennaTools) and used the namespace `vieTools`, but I don't really like it that much. The issue I have with these prefixes is that the functions are going to be used all over the ViennaTools libraries and especially in ViennaPS, where everything is combined; a user then has to know whether a particular function is from ViennaPS, LS or Core, and use the according prefix. This seems a bit stupid to me. 

One option could be to alias the most important functions (SmartPointer in particular) in all libraries, so you have a vtSmartPointer, lsSmartPointer, and psSmartPointer, which are all the same.

Another option I could think of is to use a global namespace for all libraries, or maybe one can alias a namespace (not sure if this is possible)?

**Comment by Curve** [comment]
> Another option I could think of is to use a global namespace for all libraries, or maybe one can alias a namespace (not sure if this is possible)?

```c++
namespace x = y;
```

You could also add a `using namespace` inside the respective ViennaLS/PS... namespace
