### ISSUE TITLE
Format Error

### ISSUE THREAD

**Issue by tobre1** [ViennaTools/ViennaCore#3]
Whenever I try to run the format target in CMake, cmake-format throws this error:

> [build] Traceback (most recent call last):
> [build]   File "/Users/tobiasreiter/.local/bin/cmake-format", line 8, in <module>
> [build]     sys.exit(main())
> [build]              ^^^^^^
> [build]   File "/Users/tobiasreiter/.local/pipx/venvs/cmakelang/lib/python3.12/site-packages/cmakelang/format/__main__.py", line 633, in main
> [build]     return inner_main()
> [build]            ^^^^^^^^^^^^
> [build]   File "/Users/tobiasreiter/.local/pipx/venvs/cmakelang/lib/python3.12/site-packages/cmakelang/format/__main__.py", line 616, in inner_main
> [build]     onefile_main(infile_path, args, argparse_dict)
> [build]   File "/Users/tobiasreiter/.local/pipx/venvs/cmakelang/lib/python3.12/site-packages/cmakelang/format/__main__.py", line 508, in onefile_main
> [build]     config_dict = get_config(infile_path, args.config_files)
> [build]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [build]   File "/Users/tobiasreiter/.local/pipx/venvs/cmakelang/lib/python3.12/site-packages/cmakelang/format/__main__.py", line 359, in get_config
> [build]     return get_configdict(configfile_paths)
> [build]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [build]   File "/Users/tobiasreiter/.local/pipx/venvs/cmakelang/lib/python3.12/site-packages/cmakelang/format/__main__.py", line 312, in get_configdict
> [build]     increment_dict = get_one_config_dict(configfile_path)
> [build]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [build]   File "/Users/tobiasreiter/.local/pipx/venvs/cmakelang/lib/python3.12/site-packages/cmakelang/format/__main__.py", line 303, in get_one_config_dict
> [build]     return try_get_configdict(configfile_path)
> [build]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [build]   File "/Users/tobiasreiter/.local/pipx/venvs/cmakelang/lib/python3.12/site-packages/cmakelang/format/__main__.py", line 256, in try_get_configdict
> [build]     raise RuntimeError("Failed to parse {} as any of yaml, json, or python"
> [build] RuntimeError: Failed to parse /Users/tobiasreiter/Code/ViennaCore/config/.cmake-format as any of yaml, json, or python

Do you know why this could happen?

**Comment by Curve** [comment]
You are missing [`pyyaml`](https://github.com/yaml/pyyaml), `cmake-format` depends on it **implicitly** - Since cmake-format is no longer maintained it does not seem like the author will explicitly depend on it any time soon sadly.
